name: Update FSPS
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update_fsps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Update the submodule
        run: git submodule foreach git pull origin master
      
      - name: Create a PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FSPS_BOT_TOKEN }}
          commit-message: Updating FSPS
          branch: update-fsps
          delete-branch: true
          push-to-fork: python-fsps/python-fsps
          title: Updating FSPS
          body: Automatically updating the FSPS submodule
          
